pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

# do this before all your .NET Core tasks
steps:
- task: Set up dotnet core@0 #DotNetCoreInstaller@0
  inputs:
    version: '2.2.105' # replace this value with the version that you need for your project
# ...

- task: Build@2 #DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need
- task: Restore@1
  script: dotnet restore